
import 'package:phone_ng/phone_ng.dart';

final Map<String, PrefixEntry> prefixMap = {
  // 08xx Series
  '0800': PrefixEntry(network: Network.unknown, type: EntryType.special),
  '0801': PrefixEntry(network: Network.mafab, type: EntryType.mobile),
  '0802': PrefixEntry(network: Network.airtel, type: EntryType.mobile),
  '0803': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0804': PrefixEntry(network: Network.ntel, type: EntryType.mobile),
  '0805': PrefixEntry(network: Network.glo, type: EntryType.mobile),
  '0806': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0807': PrefixEntry(network: Network.glo, type: EntryType.mobile),
  '0808': PrefixEntry(network: Network.airtel, type: EntryType.mobile),
  '0809': PrefixEntry(network: Network.nineMobile, type: EntryType.mobile),
  '0810': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0811': PrefixEntry(network: Network.glo, type: EntryType.mobile),
  '0812': PrefixEntry(network: Network.airtel, type: EntryType.mobile),
  '0813': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0814': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0815': PrefixEntry(network: Network.glo, type: EntryType.mobile),
  '0816': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0817': PrefixEntry(network: Network.nineMobile, type: EntryType.mobile),
  '0818': PrefixEntry(network: Network.nineMobile, type: EntryType.mobile),

  // 07xx Series
  '0700': PrefixEntry(network: Network.unknown, type: EntryType.special),
  '0701': PrefixEntry(network: Network.airtel, type: EntryType.mobile),
  '0702': PrefixEntry(network: Network.smile, type: EntryType.mobile),
  '0703': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0704': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0705': PrefixEntry(network: Network.glo, type: EntryType.mobile),
  '0706': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0707': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0708': PrefixEntry(network: Network.airtel, type: EntryType.mobile),

  // 09xx Series
  '0900': PrefixEntry(network: Network.unknown, type: EntryType.special),
  '0901': PrefixEntry(network: Network.airtel, type: EntryType.mobile),
  '0902': PrefixEntry(network: Network.airtel, type: EntryType.mobile),
  '0903': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0904': PrefixEntry(network: Network.airtel, type: EntryType.mobile),
  '0905': PrefixEntry(network: Network.glo, type: EntryType.mobile),
  '0906': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0907': PrefixEntry(network: Network.airtel, type: EntryType.mobile),
  '0908': PrefixEntry(network: Network.nineMobile, type: EntryType.mobile),
  '0909': PrefixEntry(network: Network.nineMobile, type: EntryType.mobile),
  '0911': PrefixEntry(network: Network.airtel, type: EntryType.mobile),
  '0912': PrefixEntry(network: Network.airtel, type: EntryType.mobile),
  '0913': PrefixEntry(network: Network.mtn, type: EntryType.mobile),
  '0915': PrefixEntry(network: Network.glo, type: EntryType.mobile),
  '0916': PrefixEntry(network: Network.mtn, type: EntryType.mobile),

  // Landlines (UNKNOWN/LANDLINE)
  '001': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '002': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '009': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '022': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '030': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '031': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '033': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '034': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '035': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '036': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '037': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '038': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '039': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '041': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '042': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '043': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '044': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '045': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '046': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '047': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '048': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '050': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '051': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '052': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '053': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '054': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '055': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '056': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '057': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '058': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '059': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '060': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '061': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '062': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '063': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '064': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '065': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '066': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '067': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '068': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '069': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '071': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '072': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '073': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '075': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '076': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '077': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '078': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '079': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '082': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '083': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '084': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '085': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '086': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '087': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '088': PrefixEntry(network: Network.unknown, type: EntryType.landline),
  '089': PrefixEntry(network: Network.unknown, type: EntryType.landline),
};

const countryCode = "234";
const trunkPrefix = "0";
const mobileLength =  10;
const e164Prefix = "+234";
const rfc3966Prefix = "tel:+";
const intlPrefix = "+234";




